export default {
  login: "Git-sharma",
  id: 107116350,
  node_id: "U_kgDOBmJ3Pg",
  avatar_url: "https://avatars.githubusercontent.com/u/107116350?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Git-sharma",
  html_url: "https://github.com/Git-sharma",
  followers_url: "https://api.github.com/users/Git-sharma/followers",
  following_url:
    "https://api.github.com/users/Git-sharma/following{/other_user}",
  gists_url: "https://api.github.com/users/Git-sharma/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Git-sharma/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Git-sharma/subscriptions",
  organizations_url: "https://api.github.com/users/Git-sharma/orgs",
  repos_url: "https://api.github.com/users/Git-sharma/repos",
  events_url: "https://api.github.com/users/Git-sharma/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/Git-sharma/received_events",
  type: "User",
  site_admin: false,
  name: null,
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 0,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2022-06-08T11:31:12Z",
  updated_at: "2023-11-09T04:12:18Z",
};
