export default {
  login: "Git-MishRa",
  id: 84155248,
  node_id: "MDQ6VXNlcjg0MTU1MjQ4",
  avatar_url: "https://avatars.githubusercontent.com/u/84155248?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Git-MishRa",
  html_url: "https://github.com/Git-MishRa",
  followers_url: "https://api.github.com/users/Git-MishRa/followers",
  following_url:
    "https://api.github.com/users/Git-MishRa/following{/other_user}",
  gists_url: "https://api.github.com/users/Git-MishRa/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Git-MishRa/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Git-MishRa/subscriptions",
  organizations_url: "https://api.github.com/users/Git-MishRa/orgs",
  repos_url: "https://api.github.com/users/Git-MishRa/repos",
  events_url: "https://api.github.com/users/Git-MishRa/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/Git-MishRa/received_events",
  type: "User",
  site_admin: false,
  name: "SHITENDU MISHRA",
  company: null,
  blog: "",
  location: "Chandigarh, India",
  email: null,
  hireable: null,
  bio: "Aspiring Web Developer",
  twitter_username: null,
  public_repos: 7,
  public_gists: 0,
  followers: 1,
  following: 1,
  created_at: "2021-05-13T20:45:36Z",
  updated_at: "2023-01-26T11:20:58Z",
};
